#!/usr/bin/env python

import sys
import getpass

def exit_error(error):
    print(error, file=sys.stderr)
    exit(1)

hosts_file = '/etc/hosts'

start_token = '## start-gsd'
end_token = '## end-gsd'

def play():
    hosts_file_handle = open(hosts_file, "r+")
    lines = hosts_file_handle.readlines()

    startIndex = -1

    for index, line in enumerate(lines):
        if line.strip() == start_token:
            startIndex = index

    if startIndex > -1:
        lines = lines[0:startIndex]

        hosts_file_handle.seek(0)
        hosts_file_handle.write(''.join(lines))
        hosts_file_handle.truncate()

    hosts_file_handle.close()

def main():
    if getpass.getuser() != 'root':
        exit_error('Please run script as root.')
    play()

if __name__ == "__main__":
    main()
